#!/usr/bin/python
# -*- coding: utf-8 -*-


lista = [1,2,3,"hola mundo","que tal",[1,2,3,4]]

print "Primer elemento de la lista"

print (lista[0])

print "Elemento de una lista dentro de una lista"

print lista[5][2]

