#!/usr/bin/python
# -*- coding: utf-8 -*-

numero1 = raw_input("Introduce el primer numero ")

numero2 = raw_input("Introduce el segundo nombre ")

numero3 = int(numero1)+int(numero2)

print "El resultado de la suma es "+ str(numero3)
